-- ============================================================
-- CAOS ASTRAL — Seed: enciclopedia_simbolos (lote 001)
--
-- FONTE: lote_001_enciclopedia.json, já versionado neste repo
-- (conteúdo real, não inventado) — versão "v1", tier padrão "gratis".
-- Só 5 verbetes neste lote — é o que existe hoje, não é a
-- enciclopédia inteira (nome do arquivo já indica que são lotes).
--
-- Rodar depois de 0013_enciclopedia_simbolos.sql.
-- ============================================================

insert into public.enciclopedia_simbolos
  (nome, slug, categoria, tier, nomes_alternativos, tradicoes, origem, primeiros_registros, significado, uso_historico, uso_moderno, correspondencias, bibliografia, svg_path)
values
  ('Caosphere', 'caosphere', 'magia-do-caos', 'gratis', '{"Esfera do Caos","Símbolo dos Oito Raios"}', '{"magia-do-caos"}', 'Criado no contexto da Magia do Caos moderna, ligado à Illuminates of Thanateros (fundada por Peter J. Carroll e Ray Sherwin em 1978). Não possui raiz antiga, é um símbolo do século XX.', 'Final da década de 1970 / início dos anos 1980, em publicações da tradição da Magia do Caos.', 'Uma esfera da qual partem oito setas em direções equidistantes, representando a totalidade das possibilidades de ação e crença antes de qualquer escolha específica. Cada raio pode ser lido como um elemento, uma direção ou uma linha de força potencial; a esfera central representa o vazio ou o potencial não-manifesto do qual tudo emerge.', 'Adotado como símbolo de identidade visual da própria Magia do Caos, funcionando de forma análoga a como o pentagrama representa a bruxaria ou o hexagrama representa o judaísmo, um emblema de escola de pensamento, não um artefato ritual herdado de tradições antigas.', 'Usado como marca de pertencimento à tradição, em sigilos pessoais, capas de livros e como ponto de partida visual para práticas de foco de vontade. Não carrega corpo de correspondências planetárias ou elementais fixas, cada praticante ou grupo pode atribuir significado próprio, o que é coerente com o princípio de que a crença é instrumental.', '{"elemento": "todos (símbolo pré-elemental)", "conceito_chave": "potencial não comprometido, crença como ferramenta descartável"}'::jsonb, '{"Peter J. Carroll, Liber Null & Psychonaut (1987)","Phil Hine, Condensed Chaos (1995)"}', null),
  ('Sigilo pessoal', 'sigilo-pessoal', 'magia-do-caos', 'gratis', '{"Sigilo de desejo","Método de Spare"}', '{"magia-do-caos"}', 'Desenvolvido pelo artista e ocultista britânico Austin Osman Spare no início do século XX, décadas antes da Magia do Caos ser nomeada como tradição.', 'Publicado em ''The Book of Pleasure (Self-Love)'' (1913), embora práticas de condensação de letras em símbolos existissem em grimórios anteriores de forma diferente.', 'Um símbolo abstrato construído a partir das letras de uma frase de intenção (com vogais e repetições removidas), depois estilizado até perder legibilidade verbal. A ideia central é que, uma vez que o símbolo é ''esquecido'' conscientemente e carregado ao inconsciente (o que Spare chamava de ''morte do desejo''), ele opera sem a interferência da vontade consciente, que Spare via como um obstáculo à manifestação.', 'Spare relacionava a técnica à sua própria cosmologia (o ''Zos Kia Cultus'' e o conceito de Kia como força vital individual), distinta da cerimônia ritual elaborada da Golden Dawn, da qual ele se afastou deliberadamente.', 'Peter Carroll e outros popularizaram o método como ferramenta central da Magia do Caos nos anos 1970-80, frequentemente combinado a estados de gnose induzidos por exaustão física, êxtase ou monotonia repetitiva. É hoje a técnica mais associada à tradição, ensinada de forma independente de qualquer painel de correspondências fixas.', '{"planeta": null, "elemento": null, "conceito_chave": "vontade inconsciente, esquecimento ativo, gnose"}'::jsonb, '{"Austin Osman Spare, The Book of Pleasure (1913)","Peter J. Carroll, Liber Null & Psychonaut (1987)"}', null),
  ('Ouroboros', 'ouroboros', 'magia-do-caos', 'gratis', '{"Uroboros"}', '{"hermetismo","alquimia","magia-do-caos"}', 'Egito Antigo, com adoção posterior pelo Gnosticismo, Hermetismo e Alquimia europeia.', 'Representações da serpente que devora a própria cauda aparecem em textos funerários egípcios de cerca do século XIV a.C. (como o Livro do que Há no Além-Mundo, no túmulo de Tutancâmon).', 'A serpente ou dragão circular representa o ciclo sem início nem fim: eterno retorno, unidade dos opostos, morte seguida de renascimento. Em contextos alquímicos passou a simbolizar também a unidade da matéria em transformação (solve et coagula).', 'Circulou por textos gnósticos (como referência à totalidade cósmica) e por manuscritos alquímicos medievais e renascentistas, onde aparece frequentemente com a inscrição grega ''hen to pan'' (o um, o todo).', 'Carl Jung o adotou como imagem do processo de individuação psíquica. Na Magia do Caos contemporânea, é por vezes usado como metáfora do ciclo de crença-descrença que caracteriza o uso instrumental de sistemas mágicos, vestir e depois deliberadamente descartar uma crença, sem se prender a ela como verdade permanente.', '{"elemento": "éter (em leituras alquímicas tardias)", "conceito_chave": "ciclo, autossuficiência, retorno"}'::jsonb, '{"Carl Jung, Psychology and Alchemy (1944)","Peter J. Carroll, Liber Null & Psychonaut (1987)"}', null),
  ('Sol (☉)', 'sol', 'astrologia', 'gratis', '{}', '{"astrologia"}', 'Observação astronômica documentada desde a Mesopotâmia; sistematizado como corpo astrológico na tradição helenística.', 'Associações solares com divindades (Utu/Shamash na Mesopotâmia, Rá no Egito) antecedem em muito a astrologia horoscópica greco-romana, que consolidou o Sol como um dos sete corpos clássicos por volta do século II a.C. em diante.', 'Na astrologia tradicional, representa identidade central, vitalidade e propósito consciente, o eixo em torno do qual a personalidade se organiza. No Caos Astral, esse corpo corresponde ao termo interno ''núcleo''.', 'Shamash, na Mesopotâmia, era concebido como juiz divino e guardião da ordem, o Sol como fonte de verdade e revelação, não apenas luz física. Essa camada de significado (Sol = clareza/verdade) atravessa boa parte das tradições solares posteriores.', 'Na astrologia psicológica do século XX (Dane Rudhyar entre outros), o Sol passou a ser lido como processo de individuação, não posição fixa de caráter. No produto Caos Astral, essa leitura processual é a base do termo ''núcleo'': ferramenta de organização de energia, não destino fechado.', '{"elemento": "fogo (associação tradicional, não universal entre sistemas)", "metal": "ouro (correspondência alquímica clássica)", "conceito_chave": "identidade central, vitalidade"}'::jsonb, '{"Robert Hand, Planets in Transit (1976)","Dane Rudhyar, The Astrology of Personality (1936)"}', null),
  ('Lua (☽)', 'lua', 'astrologia', 'gratis', '{}', '{"astrologia"}', 'Um dos corpos celestes mais antigos observados sistematicamente por qualquer cultura, com calendários lunares documentados na Mesopotâmia e em diversas civilizações antigas de forma independente.', 'Referências à Lua como divindade ou força astrológica aparecem em tabuinhas mesopotâmicas associadas ao deus Nanna/Sin, anteriores à própria sistematização horoscópica.', 'Representa tradicionalmente o emocional, o instintivo e o hábito, a camada de resposta automática que antecede a reflexão consciente. No Caos Astral, esse corpo corresponde ao termo interno ''fome'': o que a pessoa busca por impulso, antes de qualquer decisão deliberada.', 'Em praticamente todas as tradições astrológicas antigas, a Lua está ligada a ciclos (mensal, de marés, agrícola) e por isso frequentemente associada a mudança e reação, em contraste com a constância solar.', 'A astrologia psicológica trata a posição lunar como o padrão emocional que opera fora da consciência plena, o que a pessoa faz ''no piloto automático''. O termo Caos Astral ''fome'' foi escolhido deliberadamente para evitar a leitura passiva comum (''você é assim'') e enquadrar o dado como um impulso identificável e, portanto, administrável.', '{"elemento": "água (associação tradicional)", "conceito_chave": "instinto, hábito, resposta automática"}'::jsonb, '{"Liz Greene, Relating (1977)","Howard Sasportas, The Twelve Houses (1985)"}', null)
on conflict (slug) do update set
  nome = excluded.nome,
  categoria = excluded.categoria,
  nomes_alternativos = excluded.nomes_alternativos,
  tradicoes = excluded.tradicoes,
  origem = excluded.origem,
  primeiros_registros = excluded.primeiros_registros,
  significado = excluded.significado,
  uso_historico = excluded.uso_historico,
  uso_moderno = excluded.uso_moderno,
  correspondencias = excluded.correspondencias,
  bibliografia = excluded.bibliografia,
  svg_path = excluded.svg_path;
