-- ============================================================
-- CAOS ASTRAL — Seed: cenas_grau (360 graus)
--
-- RECONSTRUÍDO em 01/08 pelo agente de front, depois da troca de
-- projeto Supabase (banco antigo deletado, projeto novo vazio).
--
-- FONTE: este conteúdo NÃO foi inventado nem reconstruído de memória —
-- veio direto de graus-caos-astral/graus-caos-astral-completo.json,
-- que já estava versionado neste mesmo repo (conteúdo autoral
-- 100% original do Micael, 360 entradas, validado 1:1 — 12 signos ×
-- 30 graus, todos os campos presentes, sem duplicata/falta). Esse JSON
-- é a fonte de verdade; este .sql é só a mesma informação em formato
-- de INSERT.
--
-- Rodar depois de 0001_schema.sql (precisa da tabela cenas_grau já
-- existir, com a coluna 'versao' — compute-natal-chart filtra
-- .eq("versao", "v1")).
-- ============================================================

insert into public.cenas_grau (signo, grau, decanato, tempero, imagem, leitura, versao) values
  ('áries', 1, 1, 'marte', 'uma faísca salta de duas pedras batendo às cegas no escuro.', 'o impulso nasce antes de qualquer plano, não é erro, é o motor tentando ligar. serve pra começar, não pra sustentar sozinho.', 'v1'),
  ('áries', 2, 1, 'marte', 'um corredor dispara antes do tiro de largada soar.', 'a pressa aqui não é falta de disciplina, é o núcleo testando se a pista já existe.', 'v1'),
  ('áries', 3, 1, 'marte', 'uma porta é chutada aberta antes de alguém verificar o que tem do outro lado.', 'entrar sem checar é o risco e o combustível do mesmo gesto, o que tem do outro lado só se descobre depois.', 'v1'),
  ('áries', 4, 1, 'marte', 'um recém-nascido solta o primeiro grito antes de saber que existe um mundo fora.', 'presença antes de contexto. reivindicar espaço não precisa de permissão prévia.', 'v1'),
  ('áries', 5, 1, 'marte', 'uma lâmina recém-forjada, ainda quente, corta o primeiro objeto que encontra.', 'força recém-feita não escolhe alvo com cuidado ainda, ela só corta pra confirmar que corta.', 'v1'),
  ('áries', 6, 1, 'marte', 'um cachorro puxa a coleira na direção contrária de quem segura.', 'o impulso quer ir mais rápido que quem seria responsável por ele. a tensão é o dado, não o defeito.', 'v1'),
  ('áries', 7, 1, 'marte', 'um fósforo é riscado dentro de um cômodo cheio de gás.', 'ação sem inventário do risco. pode ser coragem ou descuido, a diferença só aparece depois do estalo.', 'v1'),
  ('áries', 8, 1, 'marte', 'uma criança derruba a torre de blocos só pra ver ela cair.', 'destruir também é forma de aprender a mecânica de alguma coisa. não é sabotagem, é curiosidade crua.', 'v1'),
  ('áries', 9, 1, 'marte', 'um motor é ligado antes do óleo terminar de circular.', 'pressa de funcionar antes de estar pronto, pode falhar, mas também é assim que motor aprende a rodar.', 'v1'),
  ('áries', 10, 1, 'marte', 'uma flecha já solta, ainda no ar, sem poder ser chamada de volta.', 'decisão que já não aceita revisão. depois desse grau, o que importa é mirar antes, não depois.', 'v1'),
  ('áries', 11, 2, 'sol', 'um ator pisa no palco antes de decorar a última fala.', 'performar antes de dominar. a plateia raramente nota o que falta, só quem está no palco sabe.', 'v1'),
  ('áries', 12, 2, 'sol', 'uma bandeira é fincada no topo antes de contar quantos já chegaram lá.', 'reivindicar o topo antes de confirmar a companhia. vitória e solidão chegam juntas nesse grau.', 'v1'),
  ('áries', 13, 2, 'sol', 'um leão marca território rugindo, sem checar se há outro leão por perto.', 'presença que ocupa espaço primeiro, negocia depois, ou nunca.', 'v1'),
  ('áries', 14, 2, 'sol', 'alguém assina o próprio nome em letra garrafal, embaixo de uma promessa que ainda não cumpriu.', 'o nome já ocupa o espaço que o resultado ainda vai ter que preencher.', 'v1'),
  ('áries', 15, 2, 'sol', 'uma vitrine é montada com o produto ainda incompleto.', 'mostrar antes de terminar. funciona se o resto for entregue rápido, se não, vira só fachada.', 'v1'),
  ('áries', 16, 2, 'sol', 'um general aponta a espada pro horizonte antes de contar os próprios soldados.', 'convicção que sai na frente do inventário. quem segue por trás precisa ser perguntado, não presumido.', 'v1'),
  ('áries', 17, 2, 'sol', 'um foguete de artifício sobe sozinho, barulhento, sem plateia nenhuma olhando.', 'brilhar não depende de quem está olhando, mas sem ninguém olhando, a energia também se perde rápido.', 'v1'),
  ('áries', 18, 2, 'sol', 'uma pessoa se declara campeã antes do juiz apitar o fim do jogo.', 'confiança que aposta no resultado antes de garanti-lo. pode ser profecia ou pode ser vexame, o jogo ainda não acabou.', 'v1'),
  ('áries', 19, 2, 'sol', 'uma fogueira é acesa alta demais pro tamanho da lenha que a sustenta.', 'entusiasmo maior que a estrutura disponível. bonito enquanto dura, exige mais lenha rápido.', 'v1'),
  ('áries', 20, 2, 'sol', 'um espelho é quebrado só pra ver os cacos multiplicando o próprio reflexo.', 'precisar de mais de uma imagem de si pra se sentir inteiro. cada caco ainda é você, só fragmentado.', 'v1'),
  ('áries', 21, 3, 'júpiter', 'um cavaleiro cruza a fronteira do mapa conhecido sem perguntar o que tem depois.', 'ir além do que já foi testado, sem esperar relatório de quem já foi lá.', 'v1'),
  ('áries', 22, 3, 'júpiter', 'uma seta é apontada pro horizonte mais distante que os olhos alcançam.', 'mirar mais longe do que os olhos alcançam. a pontaria aqui é fé funcional, não garantia.', 'v1'),
  ('áries', 23, 3, 'júpiter', 'alguém prega um sermão pra uma plateia que ainda não chegou.', 'convicção que fala antes de ter quem escute. ou é visão, ou é ensaio, só o tempo separa as duas.', 'v1'),
  ('áries', 24, 3, 'júpiter', 'um viajante joga fora o mapa e confia só na bússola.', 'trocar instrução externa por direção interna. funciona se a bússola for confiável, e só dá pra saber tentando.', 'v1'),
  ('áries', 25, 3, 'júpiter', 'um professor bate o livro na mesa no meio da própria explicação, exigindo mais.', 'convicção que empurra além do previsto, mesmo no meio do próprio raciocínio.', 'v1'),
  ('áries', 26, 3, 'júpiter', 'uma trombeta anuncia a guerra antes do exército terminar de se formar.', 'declarar antes de estar pronto, o anúncio vira pressão pra alcançar o que já foi prometido.', 'v1'),
  ('áries', 27, 3, 'júpiter', 'um profeta grita a verdade numa praça vazia.', 'convicção que não precisa de plateia pra ser real, mas sem eco, fica sem saber se acertou.', 'v1'),
  ('áries', 28, 3, 'júpiter', 'um explorador planta a bandeira num pico ainda coberto de neblina, sem ver o outro lado.', 'reivindicar a conquista antes de ver o que tem do outro lado. coragem e pressa dividem o mesmo gesto.', 'v1'),
  ('áries', 29, 3, 'júpiter', 'um atleta cruza a linha de chegada e já aponta pro próximo campeonato.', 'nunca descansar na conquista feita, o grau que já vive no próximo ciclo antes de fechar o atual.', 'v1'),
  ('áries', 30, 3, 'júpiter', 'um foguete deixa a atmosfera, motor rugindo, sem olhar pra trás pro chão que deixou.', 'ruptura total com o que ficou pra trás. fim de um ciclo que não pede licença pra outro começar. (grau anarético)', 'v1'),
  ('touro', 1, 1, 'vênus', 'Uma mão fecha em volta de uma fruta madura antes de perguntar se pode colher.', 'O corpo quer primeiro, pergunta depois. Desejo cru não pede licença, só reconhecimento.', 'v1'),
  ('touro', 2, 1, 'vênus', 'Um bebê agarra o dedo de quem o segura e não solta.', 'Segurar é o primeiro modo de confirmar que algo é seu.', 'v1'),
  ('touro', 3, 1, 'vênus', 'Uma raiz se enterra mais fundo antes de a árvore crescer um centímetro visível.', 'Construir base invisível antes de qualquer resultado que apareça por fora.', 'v1'),
  ('touro', 4, 1, 'vênus', 'Alguém prova o primeiro gole de um vinho e fecha os olhos.', 'Prazer que exige atenção total pra ser sentido de verdade, não só consumido.', 'v1'),
  ('touro', 5, 1, 'vênus', 'Um cofre é trancado antes mesmo de guardar o que ainda não chegou.', 'Proteger o que ainda vai vir. Prevenção que às vezes chega cedo demais.', 'v1'),
  ('touro', 6, 1, 'vênus', 'Uma vaca pasta devagar num campo enorme, sem pressa de terminar.', 'Ritmo que não se apressa por ninguém, o tempo dela é a única métrica que importa.', 'v1'),
  ('touro', 7, 1, 'vênus', 'Uma pedra preciosa é encontrada em bruto, ainda coberta de terra.', 'Valor real que ainda não foi lapidado nem reconhecido por ninguém além de quem achou.', 'v1'),
  ('touro', 8, 1, 'vênus', 'Duas mãos amassam barro até virar forma.', 'Paciência física que transforma matéria bruta em algo com propósito.', 'v1'),
  ('touro', 9, 1, 'vênus', 'Um cão enterra um osso num lugar que só ele lembra.', 'Guardar recursos com uma lógica que só faz sentido pra quem guardou.', 'v1'),
  ('touro', 10, 1, 'vênus', 'Uma âncora é lançada e prende no fundo do mar.', 'Parar de vez, fincar posição, fim do decanato: não se mover mais até que valha a pena.', 'v1'),
  ('touro', 11, 2, 'mercúrio', 'Um joalheiro examina uma pedra sob lupa antes de dar o preço.', 'Avaliar com precisão o que antes era só desejo cru. O valor exige exame, não só vontade.', 'v1'),
  ('touro', 12, 2, 'mercúrio', 'Uma balança comercial pesa grãos, um punhado de cada vez.', 'Medir com cuidado o que se troca, prazer sem cálculo vira prejuízo.', 'v1'),
  ('touro', 13, 2, 'mercúrio', 'Um agricultor testa a terra com os dedos antes de plantar.', 'Verificar a condição real antes de investir esforço. Sentir o material, não assumir.', 'v1'),
  ('touro', 14, 2, 'mercúrio', 'Uma receita antiga é seguida à risca, colher por colher.', 'Repetir o que já funcionou, sem improviso, segurança que vem da fórmula testada.', 'v1'),
  ('touro', 15, 2, 'mercúrio', 'Um contador soma moedas numa mesa de madeira gasta.', 'Cuidar do que já existe, centavo por centavo, antes de sonhar com mais.', 'v1'),
  ('touro', 16, 2, 'mercúrio', 'Um artesão lixa a mesma superfície pela décima vez, buscando o acabamento certo.', 'Repetição que refina, não que cansa. O resultado só aparece depois de insistir.', 'v1'),
  ('touro', 17, 2, 'mercúrio', 'Um fazendeiro conserta a cerca antes que o gado escape.', 'Manutenção que evita perda maior depois. Prevenção enfadonha, mas eficaz.', 'v1'),
  ('touro', 18, 2, 'mercúrio', 'Uma costureira mede o tecido duas vezes antes de cortar uma vez.', 'Cautela que evita desperdício. O cálculo aqui protege o material, não o ego.', 'v1'),
  ('touro', 19, 2, 'mercúrio', 'Um comerciante organiza sua mercadoria em fileiras exatas.', 'Ordem que facilita o próximo passo, o que está arrumado já está meio resolvido.', 'v1'),
  ('touro', 20, 2, 'mercúrio', 'Uma mesa farta é posta, prato por prato, antes dos convidados chegarem.', 'Preparar fartura com antecedência. O que sustenta os outros também exige planejamento.', 'v1'),
  ('touro', 21, 3, 'saturno', 'Uma muralha de pedra é erguida bloco por bloco, sem pressa de terminar.', 'Construção que aceita ser lenta, porque o que se ergue rápido também cai rápido.', 'v1'),
  ('touro', 22, 3, 'saturno', 'Um carvalho antigo não se move nem com vento forte.', 'Raiz funda que recusa ceder, força que não precisa provar nada, só permanece.', 'v1'),
  ('touro', 23, 3, 'saturno', 'Um cofre de banco é fechado com três chaves diferentes, cada uma com um guardião.', 'Proteção que distribui responsabilidade, o valor grande demais pra confiar numa mão só.', 'v1'),
  ('touro', 24, 3, 'saturno', 'Um fazendeiro guarda grãos suficientes pra sobreviver ao inverno mais longo.', 'Provisão pensada pro pior cenário, não só pro dia de hoje.', 'v1'),
  ('touro', 25, 3, 'saturno', 'Uma estátua de pedra resiste séculos ao tempo, sem trocar de expressão.', 'Permanência que não pede aprovação de ninguém, só dura.', 'v1'),
  ('touro', 26, 3, 'saturno', 'Um cofre-forte é escondido atrás de uma parede comum, sem nenhuma marca visível.', 'Guardar valor sem ostentar, proteção que aposta na discrição, não na exibição.', 'v1'),
  ('touro', 27, 3, 'saturno', 'Um velho agricultor ainda planta árvores que só darão fruto depois que ele morrer.', 'Investir em algo que não vai colher, construir legado maior que a própria vida.', 'v1'),
  ('touro', 28, 3, 'saturno', 'Uma montanha de sal se acumula lentamente numa salina, grão por grão.', 'Acúmulo que não tem pressa nenhuma, o resultado só aparece depois de muito tempo repetindo o mesmo gesto.', 'v1'),
  ('touro', 29, 3, 'saturno', 'Um testamento é lacrado e guardado num cofre até a hora certa de ser aberto.', 'O que foi decidido com cuidado espera o momento certo pra valer.', 'v1'),
  ('touro', 30, 3, 'saturno', 'Uma pedra fundamental é assentada, e sobre ela toda a construção seguinte vai se apoiar.', 'O que se decide agora sustenta tudo que vem depois, grau anarético que fecha o ciclo virando alicerce.', 'v1'),
  ('gemeos', 1, 1, 'mercúrio', 'Duas crianças trocam segredos sussurrando ao mesmo tempo, sem esperar a vez uma da outra.', 'Trocar informação rápido demais pra processar tudo, o impulso de falar chega antes do de ouvir.', 'v1'),
  ('gemeos', 2, 1, 'mercúrio', 'Um telefone toca em duas casas ao mesmo tempo.', 'Estar em dois lugares ao mesmo tempo, mesmo sem sair do lugar.', 'v1'),
  ('gemeos', 3, 1, 'mercúrio', 'Uma pomba-correio carrega duas mensagens contraditórias em asas diferentes.', 'Duas versões da mesma verdade, ambas parcialmente certas.', 'v1'),
  ('gemeos', 4, 1, 'mercúrio', 'Um papagaio repete uma frase que ouviu sem entender o que ela significa.', 'Repetir informação antes de digerir seu sentido, comunicação que ainda não virou compreensão.', 'v1'),
  ('gemeos', 5, 1, 'mercúrio', 'Duas crianças gêmeas terminam a frase uma da outra.', 'Pensamento que se completa em dupla, mais rápido do que sozinho.', 'v1'),
  ('gemeos', 6, 1, 'mercúrio', 'Uma carta é escrita e reescrita três vezes antes de ser enviada.', 'A mente girando em volta da própria formulação, tentando acertar o tom certo.', 'v1'),
  ('gemeos', 7, 1, 'mercúrio', 'Um vendedor ambulante grita o preço da mercadoria pra quem passa apressado.', 'Informação lançada rápido, sem garantia de que alguém pare pra ouvir.', 'v1'),
  ('gemeos', 8, 1, 'mercúrio', 'Uma criança aprende a mesma palavra em dois idiomas no mesmo dia.', 'A mente absorvendo mais de um sistema ao mesmo tempo, sem cansar.', 'v1'),
  ('gemeos', 9, 1, 'mercúrio', 'Um jornal impresso sai com a tinta ainda fresca, borrando ao toque.', 'Notícia tão nova que ainda nem terminou de se fixar.', 'v1'),
  ('gemeos', 10, 1, 'mercúrio', 'Um bilhete é passado de mão em mão numa sala de aula até chegar torto ao destino.', 'A mensagem muda de forma a cada mão que a repassa, fim do decanato: a informação já não é mais a original.', 'v1'),
  ('gemeos', 11, 2, 'vênus', 'Duas pessoas conversam à mesa de um café, cada uma esperando a vez certa de falar.', 'Diálogo que aprende timing, trocar já não é só falar rápido, é escutar também.', 'v1'),
  ('gemeos', 12, 2, 'vênus', 'Uma carta de amor é escrita com caligrafia cuidadosa, cada palavra pesada antes de ser escrita.', 'Comunicação que já cuida do efeito que vai causar no outro.', 'v1'),
  ('gemeos', 13, 2, 'vênus', 'Dois comerciantes fecham negócio com um aperto de mão, sem contrato assinado.', 'Confiar na palavra dada, troca que aposta na relação, não só no documento.', 'v1'),
  ('gemeos', 14, 2, 'vênus', 'Um casal de dançarinos espelha os passos um do outro sem combinar antes.', 'Sincronia que nasce de prestar atenção no outro, não de plano prévio.', 'v1'),
  ('gemeos', 15, 2, 'vênus', 'Uma sala de negociação tem duas cadeiras de frente uma pra outra, mesma altura.', 'Diálogo que só funciona quando nenhum dos dois lados fala de cima.', 'v1'),
  ('gemeos', 16, 2, 'vênus', 'Um mediador senta entre duas partes brigando, sem tomar lado nenhum.', 'Equilíbrio que exige não escolher, a solução vem do meio, não de um dos extremos.', 'v1'),
  ('gemeos', 17, 2, 'vênus', 'Duas cartas são trocadas ao mesmo tempo pelo correio, cruzando no caminho.', 'Duas pessoas dizendo a mesma coisa sem saber que a outra já tinha dito.', 'v1'),
  ('gemeos', 18, 2, 'vênus', 'Um casal decide, junto, o nome que vão dar ao filho.', 'Decisão que só existe porque duas vontades se encontraram no meio.', 'v1'),
  ('gemeos', 19, 2, 'vênus', 'Uma balança de comerciante equilibra perfeitamente dois pesos diferentes.', 'Equilíbrio real, não fingido, as duas partes pesam o que dizem pesar.', 'v1'),
  ('gemeos', 20, 2, 'vênus', 'Um par de luvas é costurado de forma idêntica, mão esquerda e direita.', 'Simetria que serve pros dois lados igualmente, fim do decanato: a troca virou parceria.', 'v1'),
  ('gemeos', 21, 3, 'saturno', 'Um telégrafo transmite código através de fios que cruzam um continente inteiro.', 'A mensagem virou sistema, não depende mais de quem fala, só do código combinado.', 'v1'),
  ('gemeos', 22, 3, 'saturno', 'Um arquivista organiza milhares de cartas por data, sem ler o conteúdo de nenhuma.', 'Informação tratada como estrutura, não como sentimento, frieza que serve pra não se perder no meio de tanto dado.', 'v1'),
  ('gemeos', 23, 3, 'saturno', 'Uma rede de sinais de fumaça conecta postos de vigia distantes um do outro.', 'Comunicação que já não depende de proximidade, só do sistema estar de pé.', 'v1'),
  ('gemeos', 24, 3, 'saturno', 'Um matemático prova um teorema usando só símbolos, sem nenhuma palavra.', 'Linguagem que abandona a ambiguidade da fala comum em troca de precisão total.', 'v1'),
  ('gemeos', 25, 3, 'saturno', 'Um grupo de estranhos se organiza em silêncio, cada um sabendo exatamente sua função.', 'Coordenação que dispensa conversa, o sistema já foi combinado antes, agora só se executa.', 'v1'),
  ('gemeos', 26, 3, 'saturno', 'Uma biblioteca cataloga livros num sistema numérico que qualquer bibliotecário do mundo entende.', 'Linguagem universal que troca calor humano por alcance máximo.', 'v1'),
  ('gemeos', 27, 3, 'saturno', 'Um relógio de estação sincroniza o horário de uma cidade inteira.', 'Um único sinal organizando o comportamento de milhares de pessoas ao mesmo tempo.', 'v1'),
  ('gemeos', 28, 3, 'saturno', 'Uma rede de estradas conecta cidades que nunca se falaram diretamente.', 'Conexão que existe mesmo sem contato direto, infraestrutura no lugar de intimidade.', 'v1'),
  ('gemeos', 29, 3, 'saturno', 'Um satélite retransmite um sinal pra milhões de aparelhos ao mesmo tempo.', 'Alcance imenso, contato zero. Informação que chega em todo lugar e não pertence a ninguém em particular.', 'v1'),
  ('gemeos', 30, 3, 'saturno', 'Um código é traduzido automaticamente pra cem idiomas diferentes ao mesmo tempo.', 'Comunicação que se multiplica até perder o rosto de quem falou primeiro, grau anarético: fim de um jeito de trocar, início de outro totalmente impessoal.', 'v1'),
  ('cancer', 1, 1, 'lua', 'Um recém-nascido procura o calor do peito da mãe antes de abrir os olhos.', 'Instinto que age antes da consciência, buscar proteção nem precisa ser aprendido.', 'v1'),
  ('cancer', 2, 1, 'lua', 'Um caranguejo recua pra dentro da própria concha ao menor sinal de perigo.', 'Proteção automática. Recuar aqui não é fraqueza, é reflexo de sobrevivência.', 'v1'),
  ('cancer', 3, 1, 'lua', 'Uma mãe pássaro cobre os filhotes com as asas durante a tempestade.', 'Abrigo que se oferece sem cálculo, só resposta direta ao perigo.', 'v1'),
  ('cancer', 4, 1, 'lua', 'Uma criança segura o cobertor da infância mesmo já crescida.', 'Memória do conforto antigo que ainda ancora, mesmo sem necessidade prática.', 'v1'),
  ('cancer', 5, 1, 'lua', 'Uma maré sobe e cobre a praia inteira antes de recuar de novo.', 'Ciclo emocional que vai e volta sozinho, sem pedir licença pro relógio.', 'v1'),
  ('cancer', 6, 1, 'lua', 'Um cão fareja o cheiro de casa a quilômetros de distância.', 'Reconhecer pertencimento pelo instinto, antes de qualquer explicação racional.', 'v1'),
  ('cancer', 7, 1, 'lua', 'Uma criança chora ao ver a mãe sair da sala, mesmo sabendo que ela volta.', 'Medo de abandono que existe mesmo quando a razão já sabe que está seguro.', 'v1'),
  ('cancer', 8, 1, 'lua', 'Um ninho é forrado de penas macias antes do primeiro ovo ser posto.', 'Preparar o abrigo antes mesmo de precisar dele, cuidado que antecipa a necessidade.', 'v1'),
  ('cancer', 9, 1, 'lua', 'Uma concha vazia é carregada pela maré até a areia, ainda com a forma de quem já morou nela.', 'O formato de um lar antigo que permanece mesmo depois que quem morava foi embora.', 'v1'),
  ('cancer', 10, 1, 'lua', 'Uma criança dorme enroscada, protegendo o peito com os braços cruzados.', 'Proteger o centro mole de si mesmo, mesmo dormindo, mesmo sem ameaça visível.', 'v1'),
  ('cancer', 11, 2, 'marte', 'Uma mãe ursa ataca sem hesitar qualquer coisa que se aproxime dos filhotes.', 'Proteção que vira força total quando o que se ama está ameaçado.', 'v1'),
  ('cancer', 12, 2, 'marte', 'Um portão de ferro é trancado com três fechaduras diferentes.', 'Defesa redundante, quando o medo é grande, uma trava só nunca parece suficiente.', 'v1'),
  ('cancer', 13, 2, 'marte', 'Um cão de guarda não dorme enquanto sente um estranho perto do quintal.', 'Vigilância que não descansa até a ameaça sumir de vez.', 'v1'),
  ('cancer', 14, 2, 'marte', 'Uma família esconde o que é mais precioso embaixo do próprio chão da casa.', 'Proteger o que importa escondendo, não expondo, segurança que aposta no segredo.', 'v1'),
  ('cancer', 15, 2, 'marte', 'Uma serpente protege seus ovos enrolando o corpo inteiro ao redor deles.', 'Proteção que ocupa todo o espaço disponível, sem deixar brecha nenhuma.', 'v1'),
  ('cancer', 16, 2, 'marte', 'Uma fortaleza é construída com um único portão estreito, fácil de defender.', 'Reduzir os pontos fracos ao mínimo possível, proteção que pensa como ataque.', 'v1'),
  ('cancer', 17, 2, 'marte', 'Uma mulher esconde uma faca sob o travesseiro antes de dormir sozinha.', 'Preparar defesa mesmo sem ameaça confirmada, instinto que não relaxa fácil.', 'v1'),
  ('cancer', 18, 2, 'marte', 'Um lobo marca o território com o próprio cheiro, avisando os outros à distância.', 'Proteção que age antes do conflito, avisando limite sem precisar brigar ainda.', 'v1'),
  ('cancer', 19, 2, 'marte', 'Uma criança bate em quem tentou machucar o irmão mais novo.', 'Agressão que nasce só quando é preciso proteger alguém mais vulnerável.', 'v1'),
  ('cancer', 20, 2, 'marte', 'Uma casa é cercada por um muro alto, com cacos de vidro no topo.', 'Defesa que vira também isolamento, proteger tanto que ninguém mais entra, nem quem devia.', 'v1'),
  ('cancer', 21, 3, 'júpiter', 'Uma casa abre as portas pra abrigar quem perdeu a própria durante a enchente.', 'O cuidado que cabia só na família se expande pra quem precisa, mesmo sendo estranho.', 'v1'),
  ('cancer', 22, 3, 'júpiter', 'Uma mãe adota um filhote de outra espécie que perdeu a própria mãe.', 'Instinto de nutrir que ultrapassa os limites do próprio sangue.', 'v1'),
  ('cancer', 23, 3, 'júpiter', 'Uma cozinha comunitária alimenta o bairro inteiro sem cobrar nada.', 'Nutrição que deixou de ser só da própria casa e virou oferta pra qualquer um com fome.', 'v1'),
  ('cancer', 24, 3, 'júpiter', 'Um rio transborda e irriga terras que nunca tinham visto água antes.', 'Transbordamento que, ao invés de destruir, nutre o que estava seco.', 'v1'),
  ('cancer', 25, 3, 'júpiter', 'Uma freira acolhe crianças órfãs de guerras que não são a dela.', 'Proteção que escolhe abraçar o mundo inteiro como família, não só quem já nasceu dentro dela.', 'v1'),
  ('cancer', 26, 3, 'júpiter', 'Uma casa de portas sempre abertas nunca sabe quantos vão dormir lá à noite.', 'Hospitalidade sem controle nem cálculo, o abrigo vira oferta incondicional.', 'v1'),
  ('cancer', 27, 3, 'júpiter', 'Um oceano inteiro recebe todos os rios que desembocam nele, sem discriminar a origem.', 'Acolhimento tão grande que perde a fronteira entre o que é seu e o que é de todos.', 'v1'),
  ('cancer', 28, 3, 'júpiter', 'Uma enfermeira chora junto com uma família que não é a dela, no hospital.', 'O cuidado ultrapassa o dever profissional e vira compaixão de verdade, sem cobrar nada em troca.', 'v1'),
  ('cancer', 29, 3, 'júpiter', 'Uma comunidade inteira reconstrói a casa de um vizinho que perdeu tudo no incêndio.', 'O instinto de proteger a própria casa se estende até virar responsabilidade coletiva.', 'v1'),
  ('cancer', 30, 3, 'júpiter', 'As águas de todos os rios do mundo finalmente se encontram no mesmo oceano.', 'Todo abrigo individual desemboca, no fim, num pertencimento maior que ninguém possui sozinho, grau anarético.', 'v1'),
  ('leao', 1, 1, 'sol', 'Um recém-nascido sol nasce no horizonte e ilumina tudo ao redor sem pedir licença.', 'Existir e brilhar são o mesmo gesto aqui, não precisa justificar a própria luz.', 'v1'),
  ('leao', 2, 1, 'sol', 'Uma criança dança sozinha no meio da sala, sem ninguém olhando.', 'Expressão que nasce da alegria de existir, não da aprovação de plateia nenhuma.', 'v1'),
  ('leao', 3, 1, 'sol', 'Um girassol vira o rosto inteiro na direção do sol, o dia inteiro.', 'Orientar-se pela própria fonte de vitalidade, sem se distrair com mais nada.', 'v1'),
  ('leao', 4, 1, 'sol', 'Uma criança grita "olha pra mim" antes de pular na piscina.', 'Precisar de testemunha pro próprio feito, a alegria cresce quando é vista.', 'v1'),
  ('leao', 5, 1, 'sol', 'Um leão filhote ruge pela primeira vez, um som ainda fraco, mas já seu.', 'A primeira tentativa de ocupar espaço com a própria voz, mesmo sem força ainda.', 'v1'),
  ('leao', 6, 1, 'sol', 'Uma fogueira é acesa no centro de um acampamento, e todos se aproximam do calor.', 'Presença que atrai gente ao redor sem precisar chamar ninguém.', 'v1'),
  ('leao', 7, 1, 'sol', 'Uma criança se veste com a roupa mais colorida do guarda-roupa pra ir à escola.', 'Expressão que escolhe aparecer, não se camuflar.', 'v1'),
  ('leao', 8, 1, 'sol', 'Um pavão abre a cauda inteira mesmo sem nenhuma fêmea por perto.', 'Exibir a própria beleza é, às vezes, só sobre ser inteiro, não sobre conquistar ninguém.', 'v1'),
  ('leao', 9, 1, 'sol', 'Uma criança desenha um sol enorme no centro de qualquer folha de papel.', 'Colocar a própria luz no centro da cena, instinto que nem precisa de motivo.', 'v1'),
  ('leao', 10, 1, 'sol', 'Um coração recém-formado bate pela primeira vez, sozinho, sem plateia.', 'Vitalidade que existe antes de qualquer aplauso, fim do decanato: o pulso é a primeira prova de vida.', 'v1'),
  ('leao', 11, 2, 'júpiter', 'Um rei distribui ouro pra toda a cidade no dia da própria coroação.', 'Generosidade que nasce do excesso, dar tanto quanto se tem, sem calcular o resto.', 'v1'),
  ('leao', 12, 2, 'júpiter', 'Um anfitrião serve o dobro de comida do que os convidados poderiam comer.', 'Fartura que vira gesto de amor, mesmo quando passa do necessário.', 'v1'),
  ('leao', 13, 2, 'júpiter', 'Um ator recebe aplausos de pé e faz três reverências antes de sair do palco.', 'Aceitar o reconhecimento por inteiro, sem fingir modéstia que não sente.', 'v1'),
  ('leao', 14, 2, 'júpiter', 'Um professor generoso ensina de graça pra quem não pode pagar.', 'Compartilhar o próprio brilho sem cobrar por isso, a luz que ilumina sem se apagar.', 'v1'),
  ('leao', 15, 2, 'júpiter', 'Uma festa de casamento dura três dias inteiros de celebração.', 'Comemorar em excesso porque a alegria, quando é grande de verdade, não cabe num dia só.', 'v1'),
  ('leao', 16, 2, 'júpiter', 'Um patrono financia uma orquestra inteira só pelo prazer de ver a música acontecer.', 'Generosidade que investe no brilho alheio, mesmo sem retorno garantido.', 'v1'),
  ('leao', 17, 2, 'júpiter', 'Um líder promete mais do que consegue entregar, na euforia do discurso.', 'O entusiasmo generoso às vezes ultrapassa o que a realidade permite cumprir.', 'v1'),
  ('leao', 18, 2, 'júpiter', 'Uma criança dá de presente o brinquedo favorito pro amigo que está triste.', 'Generosidade que dói um pouco, dar o que é mais precioso, não só o que sobra.', 'v1'),
  ('leao', 19, 2, 'júpiter', 'Um artista pinta um mural enorme na parede pública, sem cobrar nada pela obra.', 'Colocar a própria expressão no mundo, grande, visível, de graça.', 'v1'),
  ('leao', 20, 2, 'júpiter', 'Um circo monta a maior tenda da cidade pra caber todo mundo que quiser ver o espetáculo.', 'O desejo de incluir todo mundo na própria celebração, quanto maior a alegria, maior o convite.', 'v1'),
  ('leao', 21, 3, 'marte', 'Um campeão ergue o troféu no alto, sozinho, no centro do estádio.', 'Orgulho conquistado com esforço, o brilho aqui foi ganho, não só dado.', 'v1'),
  ('leao', 22, 3, 'marte', 'Um artista compete pelo papel principal e não aceita o segundo lugar.', 'Ambição que recusa se contentar com menos que o centro do palco.', 'v1'),
  ('leao', 23, 3, 'marte', 'Um general condecorado exibe as medalhas no peito, uma a uma.', 'Cada conquista exposta com orgulho, a prova visível do que já foi enfrentado.', 'v1'),
  ('leao', 24, 3, 'marte', 'Uma dançarina desafia a companhia inteira até conseguir o solo principal.', 'Brilhar aqui exige disputa, o centro do palco não sobra pra quem não luta por ele.', 'v1'),
  ('leao', 25, 3, 'marte', 'Um boxeador ergue os braços antes mesmo do juiz anunciar o vencedor.', 'Confiança que já comemora antes da confirmação, orgulho que aposta em si mesmo primeiro.', 'v1'),
  ('leao', 26, 3, 'marte', 'Um rei desafia qualquer pretendente ao trono pra um duelo aberto.', 'Defender o próprio brilho com as próprias mãos, sem terceirizar a disputa.', 'v1'),
  ('leao', 27, 3, 'marte', 'Um cantor solo recusa dividir os holofotes até com a própria banda.', 'Orgulho que, levado longe demais, isola quem deveria estar comemorando junto.', 'v1'),
  ('leao', 28, 3, 'marte', 'Um atleta se recusa a comemorar até quebrar o próprio recorde, não só o dos outros.', 'Competir consigo mesmo depois de já vencer todo mundo ao redor.', 'v1'),
  ('leao', 29, 3, 'marte', 'Um leão idoso ainda defende a própria posição na manada, mesmo diante de um rival mais jovem.', 'Orgulho que resiste até o fim, recusando ceder o próprio lugar sem briga.', 'v1'),
  ('leao', 30, 3, 'marte', 'Uma última vela de aniversário se apaga sozinha, e a plateia inteira aplaude de pé.', 'O brilho que se encerra, mas deixa reconhecimento atrás de si, grau anarético: fim de ciclo celebrado, não escondido.', 'v1'),
  ('virgem', 1, 1, 'mercúrio', 'Uma costureira encontra o único fio solto numa peça de roupa inteira.', 'Atenção que enxerga o detalhe que passa despercebido pra qualquer outra pessoa.', 'v1'),
  ('virgem', 2, 1, 'mercúrio', 'Um relojoeiro desmonta um mecanismo inteiro pra achar a peça exata que está errada.', 'Paciência analítica que não desiste até encontrar a causa real do problema.', 'v1'),
  ('virgem', 3, 1, 'mercúrio', 'Uma criança organiza os lápis de cor em ordem exata do arco-íris.', 'Precisar de ordem pra sentir que o mundo está certo, não é frescura, é necessidade real.', 'v1'),
  ('virgem', 4, 1, 'mercúrio', 'Um copista revisa o mesmo texto três vezes procurando erros de grafia.', 'Cuidado que se repete até ter certeza, a versão final só sai depois de exaustão.', 'v1'),
  ('virgem', 5, 1, 'mercúrio', 'Um médico examina cada sintoma separadamente antes de arriscar um diagnóstico.', 'Recusar conclusão apressada, o cuidado real exige olhar peça por peça.', 'v1'),
  ('virgem', 6, 1, 'mercúrio', 'Uma abelha operária inspeciona cada célula do favo antes de aceitar como pronta.', 'Trabalho que não aceita "quase certo", cada parte precisa estar exatamente no lugar.', 'v1'),
  ('virgem', 7, 1, 'mercúrio', 'Um contador confere a mesma soma duas vezes antes de fechar o balanço.', 'Desconfiar até da própria conta, checagem dupla como forma de cuidado, não de insegurança.', 'v1'),
  ('virgem', 8, 1, 'mercúrio', 'Uma enfermeira organiza os remédios em compartimentos com etiquetas exatas.', 'Ordem que existe pra proteger alguém de um erro que poderia custar caro.', 'v1'),
  ('virgem', 9, 1, 'mercúrio', 'Um crítico aponta o único verso fraco num poema inteiro bem escrito.', 'Enxergar a falha específica mesmo dentro de algo que já é bom, o cuidado que exige mais.', 'v1'),
  ('virgem', 10, 1, 'mercúrio', 'Um artesão lixa a mesma dobradiça até ela parar de ranger.', 'Insistir no pequeno detalhe até ele parar de incomodar, fim do decanato: nada escapa da checagem.', 'v1'),
  ('virgem', 11, 2, 'saturno', 'Um monge segue a mesma rotina exata há quarenta anos, sem falhar um dia.', 'Disciplina que virou identidade, o rigor não é imposição, é estrutura de vida.', 'v1'),
  ('virgem', 12, 2, 'saturno', 'Um mestre de obras recusa liberar a construção até cada prego estar correto.', 'Responsabilidade que não aceita atalho, mesmo sob pressão de prazo.', 'v1'),
  ('virgem', 13, 2, 'saturno', 'Um treinador exige a mesma repetição cem vezes até o movimento ficar automático.', 'Repetição exaustiva como único caminho real pra excelência de verdade.', 'v1'),
  ('virgem', 14, 2, 'saturno', 'Um funcionário público carimba cada documento seguindo o mesmo protocolo, sem exceção.', 'Seguir a regra à risca mesmo quando parece burocracia excessiva, o sistema depende disso.', 'v1'),
  ('virgem', 15, 2, 'saturno', 'Um agricultor mede a chuva todos os dias, no mesmo horário, há décadas.', 'Constância que só rende fruto depois de muito tempo repetindo o gesto exato.', 'v1'),
  ('virgem', 16, 2, 'saturno', 'Um artesão de relógios recusa entregar a peça um dia antes do previsto, mesmo pronta.', 'Cumprir o próprio padrão de qualidade, mesmo quando ninguém cobraria isso.', 'v1'),
  ('virgem', 17, 2, 'saturno', 'Um professor corrige o mesmo erro de português pela centésima vez, sem cansar o tom.', 'Paciência disciplinada que não perde a régua mesmo diante da repetição do erro alheio.', 'v1'),
  ('virgem', 18, 2, 'saturno', 'Um soldado limpa a própria arma todos os dias, mesmo sem guerra à vista.', 'Manter o padrão de prontidão mesmo quando parece desnecessário.', 'v1'),
  ('virgem', 19, 2, 'saturno', 'Um bibliotecário recatalogar um livro fora do lugar antes de fechar a biblioteca.', 'Corrigir o pequeno desvio antes que vire bagunça maior depois.', 'v1'),
  ('virgem', 20, 2, 'saturno', 'Um artesão entrega a peça só quando ela atinge o próprio padrão, não o do cliente.', 'Rigor interno que não negocia mesmo sob pressão externa, fim do decanato: a régua é sua, não emprestada.', 'v1'),
  ('virgem', 21, 3, 'vênus', 'Um chef prova o prato sete vezes ajustando o tempero, grão de sal por grão de sal.', 'Precisão que serve o prazer, não o substitui, o rigor aqui existe pra deixar algo gostoso de verdade.', 'v1'),
  ('virgem', 22, 3, 'vênus', 'Um perfumista mistura óleos numa proporção exata até o aroma ficar perfeito.', 'Refinamento que exige tanto cálculo quanto sensibilidade, arte que também é ciência.', 'v1'),
  ('virgem', 23, 3, 'vênus', 'Um jardineiro poda cada galho com cuidado exato pra manter a forma da árvore bonita.', 'Disciplina aplicada a favor da beleza, não contra ela.', 'v1'),
  ('virgem', 24, 3, 'vênus', 'Uma costureira borda um único fio de ouro numa peça de seda simples.', 'Detalhe mínimo que eleva o todo, o cuidado pequeno que faz toda a diferença visível.', 'v1'),
  ('virgem', 25, 3, 'vênus', 'Um sommelier identifica a safra exata de um vinho só pelo cheiro.', 'Sensibilidade treinada até virar precisão quase impossível de replicar.', 'v1'),
  ('virgem', 26, 3, 'vênus', 'Um confeiteiro decora um bolo com a mesma flor repetida cem vezes, cada uma idêntica à anterior.', 'Repetição meticulosa a serviço do deleite alheio, não só da própria vaidade técnica.', 'v1'),
  ('virgem', 27, 3, 'vênus', 'Um artesão de móveis escolhe a veta exata da madeira pra combinar com o resto da peça.', 'Atenção que respeita o material como ele é, sem forçar contra sua natureza.', 'v1'),
  ('virgem', 28, 3, 'vênus', 'Uma tecelã ajusta a tensão de cada fio antes de começar o tapete inteiro.', 'Preparar o detalhe invisível que vai sustentar toda a beleza visível depois.', 'v1'),
  ('virgem', 29, 3, 'vênus', 'Um mestre chocolateiro tempera o chocolate na temperatura exata, grau a grau.', 'Prazer que só existe por causa do rigor técnico por trás, nada é acidente aqui.', 'v1'),
  ('virgem', 30, 3, 'vênus', 'Uma última pincelada de verniz seca lenta, protegendo todo o trabalho feito antes dela.', 'O cuidado final que preserva tudo o que foi construído com precisão, grau anarético: o rigor vira proteção duradoura.', 'v1'),
  ('libra', 1, 1, 'vênus', 'Uma balança de mercado se equilibra perfeitamente entre dois pesos iguais.', 'O alívio de ver as duas partes finalmente no mesmo nível.', 'v1'),
  ('libra', 2, 1, 'vênus', 'Duas mãos se encontram no meio de um aperto, nenhuma apertando mais forte que a outra.', 'Encontro que só funciona quando nenhum dos lados domina o outro.', 'v1'),
  ('libra', 3, 1, 'vênus', 'Um espelho reflete um rosto de volta, exato, sem distorcer nada.', 'Precisar ver a própria imagem refletida em algo pra se sentir real.', 'v1'),
  ('libra', 4, 1, 'vênus', 'Duas taças de cristal, idênticas, são postas lado a lado numa mesa.', 'Buscar simetria mesmo em coisas pequenas, o conforto de pares que combinam.', 'v1'),
  ('libra', 5, 1, 'vênus', 'Um casal de patos nada exatamente na mesma velocidade, lado a lado.', 'Companhia que se ajusta ao ritmo do outro sem que ninguém precise pedir.', 'v1'),
  ('libra', 6, 1, 'vênus', 'Uma flor se abre em pétalas perfeitamente simétricas.', 'Beleza que nasce naturalmente equilibrada, sem esforço visível pra parecer bonita.', 'v1'),
  ('libra', 7, 1, 'vênus', 'Duas crianças dividem o mesmo doce ao meio, cada metade do mesmo tamanho.', 'Justiça instintiva, antes mesmo de aprender a palavra "justo".', 'v1'),
  ('libra', 8, 1, 'vênus', 'Um pintor mistura duas cores até achar o tom exato entre elas.', 'Buscar o ponto médio certo, nem uma cor nem outra, mas a combinação das duas.', 'v1'),
  ('libra', 9, 1, 'vênus', 'Uma dupla de dançarinos gira em perfeita simetria, sem pisar um no pé do outro.', 'Coordenação que só existe quando os dois prestam atenção no outro o tempo todo.', 'v1'),
  ('libra', 10, 1, 'vênus', 'Duas velas idênticas são acesas ao mesmo tempo, dos dois lados do altar.', 'Equilíbrio ritual, fim do decanato: harmonia pede repetição dos dois lados.', 'v1'),
  ('libra', 11, 2, 'saturno', 'Um juiz olha pros dois lados do tribunal antes de decidir, sem favorecer nenhum.', 'Justiça que exige distância de ambos os lados pra ser real.', 'v1'),
  ('libra', 12, 2, 'saturno', 'Um contrato é assinado por duas partes, cada uma com uma cópia idêntica.', 'Acordo formalizado, o equilíbrio agora depende de documento, não só de boa vontade.', 'v1'),
  ('libra', 13, 2, 'saturno', 'Um tribunal internacional pesa os argumentos de duas nações em conflito.', 'Mediação que exige neutralidade absoluta, mesmo sendo impossível agradar os dois lados por completo.', 'v1'),
  ('libra', 14, 2, 'saturno', 'Uma árbitra apita uma falta contra o próprio time que ela mais gosta.', 'Imparcialidade que exige ir contra a própria preferência quando a regra exige.', 'v1'),
  ('libra', 15, 2, 'saturno', 'Uma balança de justiça de mármore fica no centro de uma praça pública.', 'Princípio abstrato colocado acima de qualquer interesse pessoal.', 'v1'),
  ('libra', 16, 2, 'saturno', 'Um mediador de divórcio divide os bens do casal item por item, sem se emocionar.', 'Manter distância emocional pra garantir que a divisão seja justa, não apenas confortável.', 'v1'),
  ('libra', 17, 2, 'saturno', 'Um comitê vota empatado e precisa esperar um voto de minerva pra decidir.', 'Equilíbrio tão perfeito que trava a decisão, às vezes o empate exige um terceiro elemento.', 'v1'),
  ('libra', 18, 2, 'saturno', 'Uma lei é aplicada da mesma forma pro rico e pro pobre, sem exceção.', 'Justiça que só é justiça de verdade quando não muda de acordo com quem está na frente dela.', 'v1'),
  ('libra', 19, 2, 'saturno', 'Um casal assina um acordo pré-nupcial antes de decidir se casar por amor.', 'Proteger o equilíbrio futuro com estrutura fria, mesmo em meio a um sentimento quente.', 'v1'),
  ('libra', 20, 2, 'saturno', 'Uma ponte suspensa distribui o peso igualmente entre duas torres distantes.', 'Estrutura que só se sustenta porque a carga foi calculada com precisão, fim do decanato: equilíbrio virou engenharia.', 'v1'),
  ('libra', 21, 3, 'mercúrio', 'Dois embaixadores trocam propostas de paz, cada um cedendo um pouco.', 'Negociação real, onde ninguém sai com tudo que queria, mas os dois saem com algo.', 'v1'),
  ('libra', 22, 3, 'mercúrio', 'Um casal decide, depois de horas de conversa, um nome que agrada os dois.', 'Diálogo prolongado até encontrar a palavra que serve pros dois lados.', 'v1'),
  ('libra', 23, 3, 'mercúrio', 'Um vendedor e um comprador regateiam o preço até um número que os dois aceitam.', 'Acordo que nasce da conversa, não da imposição.', 'v1'),
  ('libra', 24, 3, 'mercúrio', 'Dois sócios revisam o contrato linha por linha antes de assinar juntos.', 'Cuidado mútuo que garante que nenhum dos dois saia prejudicado depois.', 'v1'),
  ('libra', 25, 3, 'mercúrio', 'Um casal terapeuta media uma discussão, dando a palavra pra cada lado, em turnos iguais.', 'Diálogo estruturado que impede que uma voz abafe a outra.', 'v1'),
  ('libra', 26, 3, 'mercúrio', 'Dois países assinam um tratado depois de anos de conversas diplomáticas.', 'Paz construída devagar, frase por frase, cláusula por cláusula.', 'v1'),
  ('libra', 27, 3, 'mercúrio', 'Um casal de tradutores simultâneos revezam a cada frase, sem atropelar um ao outro.', 'Comunicação que só flui quando cada um sabe a hora de falar e a hora de ceder.', 'v1'),
  ('libra', 28, 3, 'mercúrio', 'Uma dupla de escritores revisa o mesmo capítulo até a versão final agradar aos dois.', 'Criação compartilhada que exige ego pequeno o suficiente pra aceitar a ideia do outro.', 'v1'),
  ('libra', 29, 3, 'mercúrio', 'Dois advogados apertam as mãos depois de um acordo fechado fora do tribunal.', 'Resolver o conflito antes de chegar ao ponto de ruptura total.', 'v1'),
  ('libra', 30, 3, 'mercúrio', 'Uma balança antiga, usada por gerações, ainda pesa exatamente igual dos dois lados.', 'O equilíbrio que atravessa o tempo, testado e nunca corrompido, grau anarético: o diálogo virou tradição confiável.', 'v1'),
  ('escorpiao', 1, 1, 'marte', 'Um escorpião ergue a cauda antes mesmo de ser tocado.', 'Defesa que se prepara antes da ameaça se confirmar, intensidade que não espera pra reagir.', 'v1'),
  ('escorpiao', 2, 1, 'marte', 'Uma porta trancada esconde algo que ninguém tem permissão de ver.', 'O instinto de proteger o que é íntimo demais pra ser exposto.', 'v1'),
  ('escorpiao', 3, 1, 'marte', 'Duas pessoas se encaram em silêncio, nenhuma disposta a desviar o olhar primeiro.', 'Disputa de vontade que não precisa de palavra nenhuma pra ser sentida.', 'v1'),
  ('escorpiao', 4, 1, 'marte', 'Uma faca é afiada em segredo, longe de qualquer olhar.', 'Preparar-se pro confronto sem anunciar a ninguém que ele está vindo.', 'v1'),
  ('escorpiao', 5, 1, 'marte', 'Um vulcão borbulha por baixo da terra sem que a superfície mostre sinal nenhum.', 'Intensidade contida que ainda não decidiu se vai explodir.', 'v1'),
  ('escorpiao', 6, 1, 'marte', 'Uma serpente troca de pele, deixando o invólucro antigo largado no chão.', 'Transformação que exige abandonar completamente uma versão anterior de si.', 'v1'),
  ('escorpiao', 7, 1, 'marte', 'Alguém guarda uma carta nunca enviada dentro de uma gaveta trancada.', 'Sentimento intenso demais pra ser dito, mas real demais pra ser jogado fora.', 'v1'),
  ('escorpiao', 8, 1, 'marte', 'Um predador espera imóvel, horas, até o momento exato de atacar.', 'Paciência que serve à intensidade, o ataque só vale a pena no timing certo.', 'v1'),
  ('escorpiao', 9, 1, 'marte', 'Duas mãos se apertam com força além do necessário num cumprimento tenso.', 'Intensidade que vaza pelo corpo mesmo quando as palavras tentam parecer neutras.', 'v1'),
  ('escorpiao', 10, 1, 'marte', 'Uma fechadura é trocada depois de alguém descobrir que tinha cópia da chave.', 'Reagir com força total à sensação de traição, fim do decanato: a linha entre confiança e controle.', 'v1'),
  ('escorpiao', 11, 2, 'júpiter', 'Alguém mergulha no oceano à noite, sem saber a profundidade real da água.', 'Entregar-se ao desconhecido, confiando em algo maior que não pode ser medido.', 'v1'),
  ('escorpiao', 12, 2, 'júpiter', 'Um monge fica em silêncio absoluto por quarenta dias, buscando algo que não tem nome.', 'Intensidade que se volta pra dentro, em busca de uma verdade que a palavra não alcança.', 'v1'),
  ('escorpiao', 13, 2, 'júpiter', 'Uma pessoa chora sem motivo aparente, sentindo uma dor que não é só sua.', 'Sensibilidade que absorve mais do que consegue processar sozinha.', 'v1'),
  ('escorpiao', 14, 2, 'júpiter', 'Um xamã entra em transe guiado por tambores, perdendo a noção do próprio corpo.', 'Dissolver os limites de si mesmo em troca de contato com algo maior.', 'v1'),
  ('escorpiao', 15, 2, 'júpiter', 'Uma mulher grávida sente o próprio corpo sendo tomado por outra vida crescendo dentro dela.', 'Intensidade que aceita ser habitada por algo que não controla totalmente.', 'v1'),
  ('escorpiao', 16, 2, 'júpiter', 'Alguém perdoa quem nunca vai pedir desculpa, só pra se libertar do próprio peso.', 'Entrega que solta o controle da vingança em troca de paz interna.', 'v1'),
  ('escorpiao', 17, 2, 'júpiter', 'Um oráculo entrega uma resposta que ninguém pediu, mas todos precisavam ouvir.', 'Verdade que emerge sem ser convocada, poder que vem de fora do controle racional.', 'v1'),
  ('escorpiao', 18, 2, 'júpiter', 'Um afogado é resgatado no último segundo, entre a vida e a morte.', 'Intensidade levada ao limite absoluto, onde só resta entrega total à sorte.', 'v1'),
  ('escorpiao', 19, 2, 'júpiter', 'Alguém reza sozinho numa igreja vazia, sem esperar resposta nenhuma.', 'Fé que não exige prova, entrega completa a algo que não se pode controlar nem ver.', 'v1'),
  ('escorpiao', 20, 2, 'júpiter', 'Uma pessoa aceita finalmente que não vai entender certos lutos, só atravessá-los.', 'Render-se ao mistério da dor, fim do decanato: intensidade que aceita não ter controle total.', 'v1'),
  ('escorpiao', 21, 3, 'lua', 'Alguém guarda uma cicatriz debaixo da roupa, visível só pra quem já foi convidado a ver.', 'Vulnerabilidade que se protege, mas ainda existe, esperando o momento certo de ser mostrada.', 'v1'),
  ('escorpiao', 22, 3, 'lua', 'Um diário é escrito com cadeado, guardando segredos que nem a própria família conhece.', 'Intimidade que só se revela em condições muito específicas de confiança.', 'v1'),
  ('escorpiao', 23, 3, 'lua', 'Uma pessoa chora escondida no banheiro pra não preocupar quem ela ama.', 'Proteger os outros da própria dor, mesmo quando isso custa caro por dentro.', 'v1'),
  ('escorpiao', 24, 3, 'lua', 'Uma mãe esconde o próprio medo pra não assustar o filho doente.', 'Força que nasce de esconder a fragilidade real por trás de um rosto calmo.', 'v1'),
  ('escorpiao', 25, 3, 'lua', 'Alguém guarda a foto de quem já morreu dentro da carteira, sem mostrar pra ninguém.', 'Luto vivido em silêncio, carregado por perto, mas nunca exposto.', 'v1'),
  ('escorpiao', 26, 3, 'lua', 'Uma casa antiga guarda cartas de amor escondidas atrás de uma parede falsa.', 'Segredo protegido tão bem que só é encontrado por acidente, muito tempo depois.', 'v1'),
  ('escorpiao', 27, 3, 'lua', 'Um sobrevivente de trauma só conta a própria história pra quem já passou por algo parecido.', 'Vulnerabilidade que só se abre em presença de quem realmente pode entender.', 'v1'),
  ('escorpiao', 28, 3, 'lua', 'Alguém dorme abraçado a um objeto que pertenceu a quem já se foi.', 'Buscar conforto físico numa lembrança que não pode mais abraçar de volta.', 'v1'),
  ('escorpiao', 29, 3, 'lua', 'Uma pessoa perdoa em silêncio, sem nunca dizer isso em voz alta pra quem a machucou.', 'Cura que acontece por dentro, sem precisar de reconhecimento externo nenhum.', 'v1'),
  ('escorpiao', 30, 3, 'lua', 'Uma concha antiga é encontrada, ainda guardando dentro dela o eco baixinho do mar.', 'O que passou continua ecoando por dentro, grau anarético: intensidade que virou memória guardada, não mais ferida aberta.', 'v1'),
  ('sagitario', 1, 1, 'júpiter', 'Um cavalo dispara solto pelo campo aberto, sem cerca nenhuma à vista.', 'Liberdade que se sente antes mesmo de saber pra onde vai.', 'v1'),
  ('sagitario', 2, 1, 'júpiter', 'Uma criança pergunta "por quê" pela quinta vez seguida, sem se satisfazer com a resposta anterior.', 'Fome de sentido que não aceita explicação superficial.', 'v1'),
  ('sagitario', 3, 1, 'júpiter', 'Um mapa é desenhado com um espaço em branco enorme escrito "território desconhecido".', 'O que ainda não foi explorado atrai mais do que assusta.', 'v1'),
  ('sagitario', 4, 1, 'júpiter', 'Alguém compra uma passagem só de ida pra um lugar que nunca visitou.', 'Confiar no caminho antes mesmo de saber exatamente onde ele leva.', 'v1'),
  ('sagitario', 5, 1, 'júpiter', 'Um cachorro corre atrás do próprio horizonte, sem nunca alcançar de fato.', 'Buscar sempre mais longe, mesmo sabendo que a linha do horizonte sempre recua também.', 'v1'),
  ('sagitario', 6, 1, 'júpiter', 'Uma criança aponta pro céu perguntando o que existe depois das estrelas.', 'Curiosidade que não se contenta com os limites do que já foi explicado.', 'v1'),
  ('sagitario', 7, 1, 'júpiter', 'Um cavalo selvagem se recusa a aceitar sela pela primeira vez.', 'Resistir a qualquer coisa que pareça limitar o movimento livre.', 'v1'),
  ('sagitario', 8, 1, 'júpiter', 'Alguém sai de casa carregando só uma mochila pequena, decidido a não voltar tão cedo.', 'Leveza que escolhe liberdade no lugar de segurança conhecida.', 'v1'),
  ('sagitario', 9, 1, 'júpiter', 'Um livro de mitologia é aberto numa página aleatória, revelando uma história nunca lida antes.', 'Buscar sentido em qualquer fonte disponível, mesmo sem plano de onde vai parar.', 'v1'),
  ('sagitario', 10, 1, 'júpiter', 'Um arqueiro solta a flecha mirando mais longe do que qualquer um ali já tentou.', 'Ambição que testa o próprio limite, fim do decanato: a convicção ainda crua, mas já em movimento.', 'v1'),
  ('sagitario', 11, 2, 'marte', 'Um explorador corta caminho pela mata fechada, ignorando a trilha já demarcada.', 'Pressa de chegar que não aceita esperar pelo caminho mais seguro.', 'v1'),
  ('sagitario', 12, 2, 'marte', 'Alguém discute com um professor, recusando aceitar uma resposta só porque veio de autoridade.', 'Convicção que exige provar por si mesmo, não aceitar de segunda mão.', 'v1'),
  ('sagitario', 13, 2, 'marte', 'Um viajante troca de rota no meio da viagem, sem aviso, seguindo só um pressentimento.', 'Impulso que confia mais na intuição do que no plano original.', 'v1'),
  ('sagitario', 14, 2, 'marte', 'Um estudante debate o próprio mestre em público, defendendo uma ideia nova.', 'Convicção que não teme confronto, mesmo contra quem ensinou.', 'v1'),
  ('sagitario', 15, 2, 'marte', 'Alguém atravessa um rio a nado em vez de esperar a ponte ser construída.', 'Impaciência que prefere o risco imediato à espera segura.', 'v1'),
  ('sagitario', 16, 2, 'marte', 'Um cavaleiro corre à frente do próprio exército, sem esperar reforço.', 'Convicção que sai na frente, mesmo sem garantia de apoio.', 'v1'),
  ('sagitario', 17, 2, 'marte', 'Uma pessoa larga o emprego estável pra seguir uma ideia em que só ela acredita ainda.', 'Fé no próprio caminho forte o bastante pra abrir mão da segurança.', 'v1'),
  ('sagitario', 18, 2, 'marte', 'Um filósofo desafia publicamente a crença mais aceita da sua época.', 'Convicção que não recua diante da opinião da maioria.', 'v1'),
  ('sagitario', 19, 2, 'marte', 'Alguém sobe uma montanha sem guia, confiando só no próprio instinto de direção.', 'Fé em si mesmo levada ao ponto de dispensar ajuda externa.', 'v1'),
  ('sagitario', 20, 2, 'marte', 'Um jovem discute com os pais, insistindo em estudar longe, sozinho, sem rede de apoio.', 'Convicção que escolhe a distância como preço da própria expansão, fim do decanato.', 'v1'),
  ('sagitario', 21, 3, 'sol', 'Um professor dá aula pra uma plateia lotada, contando a própria jornada como exemplo.', 'Convicção que quer ser vista e compartilhada, não só vivida em silêncio.', 'v1'),
  ('sagitario', 22, 3, 'sol', 'Alguém sobe num palco e conta, orgulhoso, a crença que descobriu sozinho.', 'Fé pessoal que se torna pública, na esperança de inspirar mais gente.', 'v1'),
  ('sagitario', 23, 3, 'sol', 'Um líder religioso funda um templo pra abrigar quem acredita na mesma verdade.', 'Convicção que cria estrutura pra durar além da vida de quem a teve primeiro.', 'v1'),
  ('sagitario', 24, 3, 'sol', 'Um escritor publica o livro que defendia uma ideia que ninguém mais aceitava antes.', 'Colocar a própria visão no mundo, mesmo sem garantia de que vão concordar.', 'v1'),
  ('sagitario', 25, 3, 'sol', 'Um professor universitário é aplaudido de pé depois de defender uma tese revolucionária.', 'Reconhecimento que confirma que a busca solitária valeu o risco.', 'v1'),
  ('sagitario', 26, 3, 'sol', 'Um viajante volta pra casa e reúne a cidade inteira pra contar o que descobriu lá fora.', 'A descoberta pessoal vira presente coletivo quando é compartilhada em voz alta.', 'v1'),
  ('sagitario', 27, 3, 'sol', 'Um mestre funda uma escola pra ensinar tudo que aprendeu sozinho, ao longo de décadas.', 'Transformar experiência individual em legado que outros podem herdar.', 'v1'),
  ('sagitario', 28, 3, 'sol', 'Alguém planta uma bandeira representando uma ideia nova no topo de uma instituição antiga.', 'Convicção que desafia a tradição abertamente, sem esconder a intenção.', 'v1'),
  ('sagitario', 29, 3, 'sol', 'Um professor aposentado ainda dá palestras lotadas, décadas depois de ter começado.', 'A busca por sentido que virou legado tão forte que continua atraindo gente.', 'v1'),
  ('sagitario', 30, 3, 'sol', 'Um mapa-múndi inteiro é finalmente completado, sem nenhum espaço em branco restando.', 'A busca que começou sem destino certo finalmente enxerga o território inteiro, grau anarético: a convicção virou visão completa.', 'v1'),
  ('capricornio', 1, 1, 'saturno', 'Uma cabra sobe um penhasco íngreme, um passo calculado de cada vez.', 'Ambição que não pula etapa, mesmo quando o topo parece longe demais.', 'v1'),
  ('capricornio', 2, 1, 'saturno', 'Um operário chega ao trabalho antes do sol nascer, todos os dias, sem exceção.', 'Disciplina que não depende de vontade, virou rotina inegociável.', 'v1'),
  ('capricornio', 3, 1, 'saturno', 'Uma criança aprende a engatinhar antes de tentar andar, sem pular a etapa.', 'Construção que respeita a ordem certa das coisas, mesmo impaciente por chegar no fim.', 'v1'),
  ('capricornio', 4, 1, 'saturno', 'Um andaime é montado nível por nível antes do prédio começar a subir de verdade.', 'Preparar a estrutura de base antes de qualquer resultado visível aparecer.', 'v1'),
  ('capricornio', 5, 1, 'saturno', 'Um relógio de sol marca a passagem do tempo sem nunca acelerar nem atrasar.', 'Aceitar o ritmo real das coisas, mesmo quando a pressa pede mais rápido.', 'v1'),
  ('capricornio', 6, 1, 'saturno', 'Um alpinista carrega o próprio peso de equipamento, subindo devagar, sem atalho.', 'Esforço que aceita ser lento porque o atalho custaria caro demais depois.', 'v1'),
  ('capricornio', 7, 1, 'saturno', 'Um aprendiz de ofício varre o chão da oficina por anos antes de tocar na primeira ferramenta.', 'Humildade que aceita começar de baixo, mesmo sabendo que merece mais.', 'v1'),
  ('capricornio', 8, 1, 'saturno', 'Uma represa é construída pedra por pedra pra conter um rio inteiro.', 'Conter uma força grande demais exige estrutura construída com paciência extrema.', 'v1'),
  ('capricornio', 9, 1, 'saturno', 'Um funcionário recusa o atalho que o chefe sugeriu, preferindo o processo correto mais longo.', 'Integridade que escolhe o caminho certo mesmo quando ninguém notaria a diferença.', 'v1'),
  ('capricornio', 10, 1, 'saturno', 'Uma escada de pedra sobe uma montanha inteira, degrau que foi entalhado há séculos.', 'Esforço acumulado que só existe porque muita gente aceitou construir devagar, fim do decanato.', 'v1'),
  ('capricornio', 11, 2, 'vênus', 'Um agricultor colhe, finalmente, o pomar que plantou anos atrás.', 'O prazer que só chega depois de muito tempo de espera, recompensa que não veio de graça.', 'v1'),
  ('capricornio', 12, 2, 'vênus', 'Um artesão vende a primeira peça feita com as próprias mãos, depois de anos de aprendizado.', 'O valor do trabalho reconhecido, finalmente, em troca justa.', 'v1'),
  ('capricornio', 13, 2, 'vênus', 'Um casal comemora bodas de ouro, cinquenta anos depois do primeiro compromisso.', 'Permanência que rende, com o tempo, uma intimidade que pressa nenhuma constrói mais rápido.', 'v1'),
  ('capricornio', 14, 2, 'vênus', 'Um executivo compra a casa que sonhava depois de décadas subindo de cargo.', 'Ambição que finalmente se converte em conforto tangível, merecido pelo esforço.', 'v1'),
  ('capricornio', 15, 2, 'vênus', 'Um professor recebe uma homenagem depois de quarenta anos de sala de aula.', 'Reconhecimento tardio que pesa mais justamente por ter demorado tanto.', 'v1'),
  ('capricornio', 16, 2, 'vênus', 'Um vinhedo antigo produz sua melhor safra depois de décadas de cultivo da mesma terra.', 'Qualidade que só a maturação do tempo consegue entregar de verdade.', 'v1'),
  ('capricornio', 17, 2, 'vênus', 'Um empresário aposenta-se e finalmente aproveita o dinheiro que levou a vida inteira acumulando.', 'O prazer adiado por tanto tempo que quase se esqueceu de existir, chegando enfim.', 'v1'),
  ('capricornio', 18, 2, 'vênus', 'Um alpinista experiente escala a montanha mais fácil, só pelo prazer, sem provar nada a ninguém.', 'Ter conquistado tanto que já pode simplesmente aproveitar, sem pressão nenhuma.', 'v1'),
  ('capricornio', 19, 2, 'vênus', 'Uma família se muda pra casa construída com as próprias economias, tijolo por tijolo.', 'O lar como resultado direto e tangível de anos de sacrifício.', 'v1'),
  ('capricornio', 20, 2, 'vênus', 'Um mestre artesão finalmente aceita um encomendante pagar o preço justo pelo que ele sabe fazer.', 'Reconhecer o próprio valor depois de anos aceitando menos do que merecia, fim do decanato.', 'v1'),
  ('capricornio', 21, 3, 'mercúrio', 'Um arquiteto revisa a planta do prédio linha por linha antes da fundação ser lançada.', 'Ambição que se apoia em cálculo exato, não só em vontade de crescer.', 'v1'),
  ('capricornio', 22, 3, 'mercúrio', 'Um estrategista planeja cada etapa da construção de um império, ano após ano.', 'Visão de longo prazo que exige paciência estrutural, não só desejo de poder.', 'v1'),
  ('capricornio', 23, 3, 'mercúrio', 'Um engenheiro testa cada viga da ponte antes de liberar a passagem de qualquer carro.', 'Responsabilidade que verifica cada detalhe antes de assumir o risco de falhar.', 'v1'),
  ('capricornio', 24, 3, 'mercúrio', 'Um CEO organiza a sucessão da empresa com anos de antecedência, treinando o substituto certo.', 'Poder que pensa além da própria permanência, construir o que continua depois de você.', 'v1'),
  ('capricornio', 25, 3, 'mercúrio', 'Um general revisa o mapa da batalha uma última vez antes de dar a ordem de avanço.', 'Ambição que não age sem plano, o controle nasce da preparação exaustiva.', 'v1'),
  ('capricornio', 26, 3, 'mercúrio', 'Um administrador público audita as próprias contas antes que alguém precise pedir.', 'Disciplina que se antecipa à cobrança, por integridade, não por medo.', 'v1'),
  ('capricornio', 27, 3, 'mercúrio', 'Um mestre de obras entrega o prédio um dia antes do prazo, sem nenhum erro estrutural.', 'Excelência que combina ambição com exatidão, chegar longe sem deixar rachadura pra trás.', 'v1'),
  ('capricornio', 28, 3, 'mercúrio', 'Um economista calcula décadas à frente o impacto de uma única decisão de hoje.', 'Poder de verdade que pensa em consequência de longo prazo, não só ganho imediato.', 'v1'),
  ('capricornio', 29, 3, 'mercúrio', 'Um professor de ofício entrega, com precisão total, tudo o que sabe pro aprendiz mais dedicado.', 'Legado transmitido com exatidão, o que foi construído com rigor merece continuar com o mesmo padrão.', 'v1'),
  ('capricornio', 30, 3, 'mercúrio', 'Uma pirâmide inteira é finalmente concluída, cada pedra encaixada no lugar exato planejado séculos atrás.', 'Ambição que atravessa gerações e se cumpre exatamente como foi arquitetada, grau anarético: estrutura permanente.', 'v1'),
  ('aquario', 1, 1, 'saturno', 'Um inventor desmonta uma máquina inteira só pra entender por que ela funciona do jeito que funciona.', 'Curiosidade fria que prefere entender o sistema a aceitá-lo como está.', 'v1'),
  ('aquario', 2, 1, 'saturno', 'Uma criança pergunta por que a regra existe, em vez de só obedecer.', 'Questionar a estrutura antes de aceitar que ela é a única forma possível.', 'v1'),
  ('aquario', 3, 1, 'saturno', 'Um cientista propõe uma teoria que contradiz tudo que já foi aceito até ali.', 'Convicção que aceita ficar isolada temporariamente em troca de estar certa depois.', 'v1'),
  ('aquario', 4, 1, 'saturno', 'Uma máquina é desligada da rede elétrica só pra testar se funciona sozinha.', 'Testar independência mesmo quando isso significa abrir mão do suporte já garantido.', 'v1'),
  ('aquario', 5, 1, 'saturno', 'Um grupo de jovens organiza um protesto sem líder nenhum no centro.', 'Estrutura horizontal que dispensa hierarquia tradicional pra funcionar.', 'v1'),
  ('aquario', 6, 1, 'saturno', 'Alguém troca o próprio nome de família por um que escolheu sozinho.', 'Reconstruir a própria identidade fora da estrutura que foi dada de nascença.', 'v1'),
  ('aquario', 7, 1, 'saturno', 'Um relógio quebrado é consertado com uma peça que nunca foi feita pra aquele modelo.', 'Solução que ignora o manual original pra fazer o sistema funcionar de outro jeito.', 'v1'),
  ('aquario', 8, 1, 'saturno', 'Uma comunidade isolada desenvolve as próprias leis, diferentes de qualquer país vizinho.', 'Criar sistema próprio, mesmo indo contra o que já era esperado ao redor.', 'v1'),
  ('aquario', 9, 1, 'saturno', 'Um professor recusa dar nota, avaliando os alunos de um jeito que a escola nunca aceitou antes.', 'Romper com o sistema estabelecido, mesmo sabendo que isso gera atrito.', 'v1'),
  ('aquario', 10, 1, 'saturno', 'Uma engrenagem nova, de formato estranho, é encaixada numa máquina antiga e ela volta a funcionar.', 'Inovação que parece errada até provar que resolve o que o sistema antigo não resolvia mais, fim do decanato.', 'v1'),
  ('aquario', 11, 2, 'mercúrio', 'Uma sala cheia de estranhos troca ideias rapidamente, cada um contribuindo um pedaço diferente.', 'Inteligência coletiva que nasce da troca rápida entre muitas cabeças diferentes.', 'v1'),
  ('aquario', 12, 2, 'mercúrio', 'Uma carta é copiada e enviada simultaneamente pra cem endereços diferentes.', 'Uma ideia que se multiplica rápido demais pra ser controlada por quem a criou.', 'v1'),
  ('aquario', 13, 2, 'mercúrio', 'Um grupo de pesquisadores em países diferentes chega à mesma descoberta ao mesmo tempo.', 'Pensamento que atravessa distância, como se a ideia já estivesse no ar esperando ser captada.', 'v1'),
  ('aquario', 14, 2, 'mercúrio', 'Uma rede de estudantes troca anotações de aula sem que nenhum professor tenha pedido isso.', 'Cooperação espontânea que nasce fora da estrutura oficial.', 'v1'),
  ('aquario', 15, 2, 'mercúrio', 'Um grupo online organiza uma causa que nenhum jornal tinha noticiado ainda.', 'Conexão que cria movimento antes mesmo de qualquer autoridade perceber que ele existe.', 'v1'),
  ('aquario', 16, 2, 'mercúrio', 'Um inventor publica a fórmula da própria descoberta de graça, pra qualquer um usar.', 'Abrir mão do controle exclusivo em nome do avanço coletivo.', 'v1'),
  ('aquario', 17, 2, 'mercúrio', 'Uma orquestra improvisada se forma com músicos que nunca tinham se visto antes.', 'Colaboração instantânea que dispensa ensaio prévio, a rede se organiza sozinha.', 'v1'),
  ('aquario', 18, 2, 'mercúrio', 'Um grupo de cientistas amadores catalogam estrelas de casas diferentes, unindo os dados numa lista só.', 'Conhecimento construído em conjunto, peça por peça, sem que ninguém precise fazer tudo sozinho.', 'v1'),
  ('aquario', 19, 2, 'mercúrio', 'Uma ideia nasce numa conversa de bar e, meses depois, aparece repetida em cidades sem contato entre si.', 'Pensamento coletivo que se espalha por caminhos que ninguém consegue rastrear direito.', 'v1'),
  ('aquario', 20, 2, 'mercúrio', 'Um grupo de vizinhos desconhecidos organiza a reconstrução da praça pública sem esperar o governo agir.', 'Rede que resolve o que a estrutura oficial ainda não resolveu, fim do decanato.', 'v1'),
  ('aquario', 21, 3, 'vênus', 'Uma cidade inteira é projetada com espaço igual pra cada família, sem favorecer ninguém.', 'Idealismo que tenta desenhar justiça direto na estrutura, não só na intenção.', 'v1'),
  ('aquario', 22, 3, 'vênus', 'Um grupo assina um manifesto pedindo direitos iguais pra todos, sem exceção.', 'Visão de futuro que recusa aceitar desigualdade como algo natural ou definitivo.', 'v1'),
  ('aquario', 23, 3, 'vênus', 'Uma cooperativa divide o lucro igualmente entre todos que trabalharam, sem hierarquia de cargo.', 'Estrutura que tenta corrigir, na prática, o que o sistema tradicional normalizou como desigual.', 'v1'),
  ('aquario', 24, 3, 'vênus', 'Um grupo de amigos cria um fundo comum pra ajudar quem precisar, sem juros, sem cobrança.', 'Solidariedade organizada como sistema, não como favor pontual.', 'v1'),
  ('aquario', 25, 3, 'vênus', 'Uma nova constituição é escrita coletivamente, frase por frase, em assembleia pública.', 'Idealismo que aceita o trabalho lento de construir consenso, em vez de impor de cima pra baixo.', 'v1'),
  ('aquario', 26, 3, 'vênus', 'Um grupo de cientistas divide livremente uma vacina, recusando patentear a fórmula.', 'Colocar o bem coletivo acima do lucro individual, mesmo abrindo mão de recompensa própria.', 'v1'),
  ('aquario', 27, 3, 'vênus', 'Uma comunidade planeja a cidade do futuro com espaço verde garantido pra todo bairro, rico ou pobre.', 'Visão que tenta garantir, de forma estrutural, que ninguém fique de fora do que é bom.', 'v1'),
  ('aquario', 28, 3, 'vênus', 'Um grupo de voluntários reconstrói uma escola pública sem cobrar nada da prefeitura.', 'Idealismo que age direto, sem esperar autorização de quem deveria ter agido primeiro.', 'v1'),
  ('aquario', 29, 3, 'vênus', 'Uma rede internacional troca sementes raras de graça entre agricultores de países diferentes.', 'Cooperação que ultrapassa fronteira, movida só pela crença de que recurso bom deveria circular livre.', 'v1'),
  ('aquario', 30, 3, 'vênus', 'Uma constelação de satélites conecta até a aldeia mais isolada do planeta à mesma rede.', 'O ideal de conexão igualitária alcançando até quem estava mais longe, grau anarético: rede que virou alcance universal.', 'v1'),
  ('peixes', 1, 1, 'júpiter', 'Alguém reza por um estranho que nunca vai saber que foi lembrado.', 'Compaixão que não exige retorno nem reconhecimento pra existir.', 'v1'),
  ('peixes', 2, 1, 'júpiter', 'Uma pessoa doa sangue sem saber quem vai recebê-lo.', 'Generosidade que se oferece ao anônimo, confiando que vai chegar a quem precisa.', 'v1'),
  ('peixes', 3, 1, 'júpiter', 'Um sonhador acredita em algo que nunca viu prova nenhuma de que é real.', 'Fé que não depende de evidência, só do desejo de que o mundo seja maior do que parece.', 'v1'),
  ('peixes', 4, 1, 'júpiter', 'Uma criança perdoa o amigo antes mesmo de ouvir o pedido de desculpa.', 'Misericórdia que chega antes de ser merecida, perdão que não calcula.', 'v1'),
  ('peixes', 5, 1, 'júpiter', 'Alguém chora vendo a notícia de uma tragédia do outro lado do mundo.', 'Sentir a dor de estranhos como se fosse próxima, fronteira entre eu e outro se dissolvendo.', 'v1'),
  ('peixes', 6, 1, 'júpiter', 'Um artista pinta um mundo que só existe na própria imaginação.', 'Criar algo que não tinha lugar no real até alguém imaginar primeiro.', 'v1'),
  ('peixes', 7, 1, 'júpiter', 'Uma pessoa oferece abrigo a um estranho que bateu na porta durante a tempestade.', 'Confiar no desconhecido além do que a prudência recomendaria.', 'v1'),
  ('peixes', 8, 1, 'júpiter', 'Um monge budista medita pedindo o fim do sofrimento de todos os seres, não só o próprio.', 'Compaixão que se recusa a parar nas próprias fronteiras.', 'v1'),
  ('peixes', 9, 1, 'júpiter', 'Uma criança inventa um amigo imaginário pra não se sentir sozinha.', 'Imaginação usada como refúgio real diante de uma solidão concreta.', 'v1'),
  ('peixes', 10, 1, 'júpiter', 'Uma vela é acesa em memória de alguém que a pessoa nunca chegou a conhecer.', 'Luto e cuidado que se estendem além do próprio círculo direto, fim do decanato.', 'v1'),
  ('peixes', 11, 2, 'lua', 'Uma pessoa sente a tristeza de um amigo antes mesmo de ele contar o que aconteceu.', 'Sensibilidade que absorve o estado emocional alheio sem precisar de explicação.', 'v1'),
  ('peixes', 12, 2, 'lua', 'Uma mãe chora junto com o filho, sentindo a dor dele como se fosse sua também.', 'Empatia tão profunda que a fronteira entre as duas dores desaparece.', 'v1'),
  ('peixes', 13, 2, 'lua', 'Alguém sonha repetidamente com uma pessoa que está longe, sem saber que ela está mal.', 'Conexão que atravessa distância física através de algum canal que a razão não explica.', 'v1'),
  ('peixes', 14, 2, 'lua', 'Uma pessoa absorve o clima de uma sala inteira só de entrar nela.', 'Sensibilidade que capta o que está no ar antes de qualquer palavra ser dita.', 'v1'),
  ('peixes', 15, 2, 'lua', 'Um terapeuta sai exausto depois de uma sessão, carregando um pouco da dor do paciente.', 'Cuidado que custa energia real de quem oferece, não é gratuito por dentro.', 'v1'),
  ('peixes', 16, 2, 'lua', 'Uma pessoa chora vendo um filme, mesmo sabendo que a história é inventada.', 'Emoção que não distingue entre real e imaginado quando a sensibilidade está aberta.', 'v1'),
  ('peixes', 17, 2, 'lua', 'Alguém sente vontade de proteger um estranho triste no ônibus, sem saber por quê.', 'Compaixão instintiva que dispensa explicação lógica pra existir.', 'v1'),
  ('peixes', 18, 2, 'lua', 'Uma família inteira sente o luto de um membro que está longe, mesmo sem saber os detalhes.', 'Vínculo emocional que continua ativo à distância, sem precisar de contato direto.', 'v1'),
  ('peixes', 19, 2, 'lua', 'Uma pessoa absorve tanto da dor alheia que esquece de cuidar da própria.', 'Generosidade emocional que, sem limite, também pode custar caro demais pra quem oferece.', 'v1'),
  ('peixes', 20, 2, 'lua', 'Alguém aprende, com o tempo, a sentir o outro sem se afogar junto na mesma dor.', 'Aprender o limite entre acolher e se dissolver por completo, fim do decanato.', 'v1'),
  ('peixes', 21, 3, 'marte', 'Uma correnteza puxa um nadador pra mais fundo do que ele pretendia ir.', 'Entrega que passa do ponto de controle, dissolver-se além do que era seguro.', 'v1'),
  ('peixes', 22, 3, 'marte', 'Alguém atravessa o luto mais difícil da vida sozinho, no silêncio absoluto da própria dor.', 'Intensidade que não pede socorro, mesmo precisando dele.', 'v1'),
  ('peixes', 23, 3, 'marte', 'Uma pessoa sacrifica o próprio conforto pra cuidar de alguém até o último momento.', 'Entrega total que não guarda nada de reserva pra si mesma.', 'v1'),
  ('peixes', 24, 3, 'marte', 'Um náufrago se agarra ao último pedaço de madeira flutuante, recusando se soltar.', 'Resistência final antes da entrega completa ao que não se pode controlar.', 'v1'),
  ('peixes', 25, 3, 'marte', 'Alguém revive, em sonho, o mesmo momento doloroso repetidas vezes, buscando um sentido escondido nele.', 'A mente insistindo em reprocessar até encontrar paz onde só havia ferida.', 'v1'),
  ('peixes', 26, 3, 'marte', 'Uma pessoa desiste de lutar contra a própria exaustão e finalmente se deixa cair de cansaço.', 'Render-se ao limite do próprio corpo depois de resistir tempo demais.', 'v1'),
  ('peixes', 27, 3, 'marte', 'Um artista termina a obra mais intensa da vida logo antes de desaparecer de cena por completo.', 'Entregar tudo que resta de si numa última expressão, sem guardar nada pra depois.', 'v1'),
  ('peixes', 28, 3, 'marte', 'Alguém solta, finalmente, o rancor mais antigo que carregava, sentindo o corpo mais leve na hora.', 'A dissolução de algo que pesava há tanto tempo que a pessoa nem lembrava mais do peso.', 'v1'),
  ('peixes', 29, 3, 'marte', 'Uma onda gigante se ergue no mar aberto antes de finalmente quebrar e se dissolver na espuma.', 'Intensidade que atinge o pico só pra se desfazer completamente logo em seguida.', 'v1'),
  ('peixes', 30, 3, 'marte', 'O último grau do zodíaco se dissolve de volta no ponto zero, onde tudo começa de novo.', 'O fim que não é fim, grau anarético que fecha a roda: só a dissolução final antes de um novo ciclo inteiro recomeçar do primeiro grau de Áries.', 'v1')
on conflict (signo, grau, versao) do update set
  decanato = excluded.decanato,
  tempero = excluded.tempero,
  imagem = excluded.imagem,
  leitura = excluded.leitura;
